name: comp0248_cw2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - kornia
  - opencv
  - numpy
  - scipy
  - pillow
  - pyqt
  - matplotlib
  - python-dateutil
  - pip
  - pip:
    - rosbags==0.10.4
    - lz4
    - evo
    - transformers
