name: comp0248_cw2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - opencv
  - pillow
  - pip
  - pip:
      - kornia
      - transformers
      - rosbags
      - evo
      - timm==0.6.13
